import os
from dotenv import load_dotenv

load_dotenv()
BACKUP_FILES_DIR = os.getenv('BACKUP_FILES_DIR')
BACKUP_FILE_ENERGY_DATA = os.getenv('BACKUP_FILE_ENERGY_DATA')
BACKUP_FILE_ROBONOMICS = os.getenv('BACKUP_FILE_ROBONOMICS')
LAST_RECORD_TRIGGER = os.getenv('LAST_RECORD_TRIGGER')
BASE_URL_BACKEND_CONSUME = os.getenv('BASE_URL_BACKEND_CONSUME')
HEADERS_ENERGY_DATA = os.getenv('HEADERS_ENERGY_DATA')
HEADERS_LAST_TRIGGER = os.getenv('HEADERS_LAST_TRIGGER')
#MAX_BACKUP_SIZE = int(os.getenv('MAX_BACKUP_SIZE'))